# https://raw.githubusercontent.com/Fueled/swiftlint-yml/master/.swiftlint.yml

disabled_rules:
  - trailing_whitespace
  - anonymous_argument_in_multiline_closure
  - anyobject_protocol
  - closure_body_length
  - conditional_returns_on_newline
  - convenience_type
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_types_order
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - inert_defer
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - prefer_nimble
  - prefer_self_in_static_references
  - prefixed_toplevel_constant
  - redundant_self_in_closure
  - required_deinit
  - self_binding
  - sorted_enum_cases
  - strict_fileprivate
  - superfluous_else
  - switch_case_on_newline
  - todo
  - trailing_closure
  - type_contents_order
  - unused_capture_list
  - vertical_whitespace_between_cases
included: # paths to include during linting. `--path` is ignored if present.
  - source/app
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - source/app/supportfiles
  - source/test
analyzer_rules:
  - unused_declaration
  - unused_import
type_body_length:
  warning: 200 
  error: 220
line_length:
  warning: 200
  error: 220 # Default is 200, so swiftlint would output an error if the file length is between 200 and 220
file_length:
  warning: 200 
  error: 220
type_name:
  min_length: 2
  max_length: 60
trailing_semicolon: error
trailing_comma:
  mandatory_comma: true
  severity: warning
function_body_length:
  warning: 15
  error: 20
statement_position:
  statement_mode: default
  severity: error
colon:
  severity: error
# private_outlet:
#   severity: warning
#   allow_private_set: true
identifier_name:
  min_length:
    warning: 4
  max_length:
    warning: 50
    error: 60
  allowed_symbols:
    - _
  excluded:
    - URL
    - on
    - no
    - qa
    - id
    - top
    - row
    - get
    - put
    - key
large_tuple: 
  warning: 6
  error: 7
return_arrow_whitespace: error
legacy_constructor: error
legacy_constant: error
leading_whitespace: error
shorthand_operator: warning
reporter: "xcode"
custom_rules:
    protocol_conformance:
        name: "Protocol Conformance"
        message: "Protocol conformance should be declared in separate extensions in the same file"
        regex: "(class|struct|extension)[[:space:]]+(?i:(?![^d]*delegate:))[^'\"()<>{},!?:]+:([^'\"<>(){},!?:]+,)+[^'\"<>(){},!?:]*\\{"
        match_kinds:
          - keyword
        severity: warning
    nested_self_usage:
        name: "Nested .self usage"
        message: ".self shouldn't be used more than once on a given statement"
        regex: "(?<!\")self\\.(?:\\p{L}+\\.)*self"
        severity: warning